// SGTRamos_SPSS_Tracking_HONEST_v1.xlsx · Sheet: Chapter Tracking · 2026-06-06
// VERIFIED columns: words (wc -w), dial_pct, flesch, fkGrade, passive_pct, codeswitch_pct
// CLAIMED/UNVERIFIED columns: cls, bis, sii, mrf, omega (labeled accordingly)
// omegaRecalc = formula-verified: Ω = 71.443 + 0.124·CLS + 0.118·BIS + 0.089·SII + 0.067·MRF
// Dup flags: PAIR A=17/18 (~90%), PAIR B=14/22 (~86%), PAIR C=26/27 (~67%)
export const CHAPTERS = [
  {ch:1, title:"The Sacred Mountain Revelation",    act:"I",  tier:"Omega Elite",words:5712, dial_pct:15.5,flesch:67.0,fkGrade:6.7,passive_pct:2.6, codeswitch_pct:3.55,cls:85, bis:84, sii:90, mrf:95, omega:106.0,  omegaRecalc:106.270, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Strong - Ω106.27 (recalc). Header: minor cosmetic double-space, low priority.",isNew:false},
  {ch:2, title:"Descent Into Baptism",              act:"I",  tier:"Omega Elite",words:6262, dial_pct:7.5, flesch:74.3,fkGrade:5.1,passive_pct:1.2, codeswitch_pct:1.29,cls:79, bis:90, sii:93, mrf:78, omega:105.0,  omegaRecalc:105.362, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"MED",  fix:"Ω105.36 (recalc). Low code-switch (1.29%) — add organic moments.",isNew:false},
  {ch:3, title:"The Genocide Algorithm",            act:"I",  tier:"Omega Elite",words:5846, dial_pct:0.0, flesch:59.4,fkGrade:7.3,passive_pct:1.6, codeswitch_pct:4.53,cls:99, bis:90, sii:92, mrf:88, omega:108.0,  omegaRecalc:108.423, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.049,fp:"LOW",  fix:"Ω108.42 (recalc). REGISTER-GATE: 0% dialogue is structural — institutional chapter.",isNew:false},
  {ch:4, title:"Pentagon, December 1969",           act:"I",  tier:"Omega Elite",words:6485, dial_pct:19.7,flesch:51.4,fkGrade:9.4,passive_pct:5.6, codeswitch_pct:0.59,cls:84, bis:91, sii:93, mrf:81, omega:106.0,  omegaRecalc:106.301, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω106.30 (recalc). REGISTER-GATE: institutional/tactical chapter. Flesch 51.4 — complex prose appropriate.",isNew:false},
  {ch:5, title:"The Ghost Protocol",               act:"I",  tier:"Omega Elite",words:5861, dial_pct:30.0,flesch:64.9,fkGrade:6.2,passive_pct:2.1, codeswitch_pct:2.61,cls:93, bis:94, sii:98, mrf:99, omega:109.0,  omegaRecalc:109.422, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω109.42 (recalc). Strong. Seed Ghost Protocol quartet foreshadowing here.",isNew:false},
  {ch:6, title:"Crucible Theorem",                 act:"I",  tier:"Omega Elite",words:5626, dial_pct:22.0,flesch:65.3,fkGrade:6.5,passive_pct:2.9, codeswitch_pct:1.00,cls:93, bis:89, sii:92, mrf:88, omega:108.0,  omegaRecalc:107.561, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω107.56 (recalc). Low code-switch (1.0%) — add 2 organic moments.",isNew:false},
  {ch:7, title:"The Boulevard Theorem",            act:"I",  tier:"Omega Elite",words:6109, dial_pct:21.5,flesch:68.3,fkGrade:5.9,passive_pct:1.5, codeswitch_pct:1.34,cls:99, bis:87, sii:94, mrf:99, omega:109.0,  omegaRecalc:108.984, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.069,fp:"LOW",  fix:"Ω108.98 (recalc). Strong. Verify Ocho Vasquez age consistency with Ch45.",isNew:false},
  {ch:8, title:"Los Records Mienten",              act:"I",  tier:"Omega Elite",words:6051, dial_pct:9.8, flesch:70.5,fkGrade:5.4,passive_pct:3.2, codeswitch_pct:4.05,cls:87.3,bis:75.5,sii:80.2,mrf:68, omega:106.5,  omegaRecalc:102.871, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.02, fp:"MED",  fix:"Ω102.87 (recalc) vs claimed 106.5 — GAP +3.6 pts. BIS 75.5 is lowest in manuscript. PTSD arc inconsistency. Guzman POV chapter.",isNew:true},
  {ch:9, title:"First Blood",                      act:"I",  tier:"Omega Elite",words:5053, dial_pct:17.9,flesch:65.3,fkGrade:7.0,passive_pct:2.3, codeswitch_pct:0.77,cls:91, bis:87, sii:95, mrf:93, omega:108.0,  omegaRecalc:107.679, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω107.68 (recalc). Ch9↔Ch10 dup flag RETIRED (v6 scan: no exact-dup). Low code-switch (0.77%).",isNew:false},
  {ch:10,title:"The Pendejo Squad",                act:"I",  tier:"Omega Elite",words:5744, dial_pct:11.3,flesch:69.2,fkGrade:5.9,passive_pct:1.8, codeswitch_pct:1.17,cls:91, bis:87, sii:95, mrf:93, omega:108.0,  omegaRecalc:107.679, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω107.68 (recalc). Fix Ramirez/Rodriguez name swap ~60% through chapter.",isNew:false},
  {ch:11,title:"Contact Contact",                  act:"I",  tier:"Omega Elite",words:6050, dial_pct:9.0, flesch:75.1,fkGrade:4.9,passive_pct:1.7, codeswitch_pct:1.40,cls:85, bis:89, sii:91, mrf:83, omega:106.0,  omegaRecalc:106.145, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω106.15 (recalc). ✅ Header fixed (v6 docx): Ch11 colon+space.",isNew:false},
  {ch:12,title:"Red Truth Revolution",             act:"I",  tier:"Omega Elite",words:5839, dial_pct:29.8,flesch:66.3,fkGrade:6.2,passive_pct:1.8, codeswitch_pct:1.18,cls:96, bis:93, sii:94, mrf:94, omega:109.0,  omegaRecalc:108.985, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.043,fp:"LOW",  fix:"Ω108.99 (recalc). Strong.",isNew:false},
  {ch:13,title:"Proud Warriors",                   act:"I",  tier:"Omega Elite",words:4489, dial_pct:15.4,flesch:70.5,fkGrade:5.5,passive_pct:1.6, codeswitch_pct:1.11,cls:97, bis:90, sii:92, mrf:88, omega:108.0,  omegaRecalc:108.175, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.043,fp:"LOW",  fix:"Ω108.18 (recalc). Strong.",isNew:false},
  {ch:14,title:"Package Sacrament",                act:"I",  tier:"Omega Elite",words:4682, dial_pct:39.9,flesch:69.3,fkGrade:5.4,passive_pct:1.1, codeswitch_pct:3.12,cls:99, bis:82, sii:92, mrf:88, omega:107.0,  omegaRecalc:107.479, dupFlag:"PAIR B",   inputStatus:"Unverified + DUP-contaminated",clmoe:0.057,fp:"HIGH", fix:"⚠ PAIR B: ~86% overlap with Ch22. Ω107.48 (recalc) — DUP-contaminated. Body dedup PENDING author decision.",isNew:false},
  {ch:15,title:"Move Like Water",                  act:"I",  tier:"Omega Elite",words:5560, dial_pct:34.2,flesch:61.5,fkGrade:6.7,passive_pct:1.7, codeswitch_pct:1.83,cls:99, bis:87, sii:94, mrf:86, omega:108.0,  omegaRecalc:108.113, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.056,fp:"LOW",  fix:"Ω108.11 (recalc). ✅ Header fixed (v6 docx): stray 'Chapter 7: Red Clay' removed.",isNew:false},
  {ch:16,title:"My Lai Massacre",                  act:"I",  tier:"Omega Elite",words:5625, dial_pct:21.2,flesch:60.8,fkGrade:7.3,passive_pct:3.7, codeswitch_pct:0.64,cls:88, bis:92, sii:90, mrf:83, omega:107.0,  omegaRecalc:106.782, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω106.78 (recalc). ✅ Header fixed (v6 docx). Very low code-switch (0.64%).",isNew:false},
  {ch:17,title:"Boundary Shift",                   act:"I",  tier:"Omega Elite",words:5915, dial_pct:8.1, flesch:65.8,fkGrade:6.5,passive_pct:0.3, codeswitch_pct:1.45,cls:77, bis:88, sii:93, mrf:85, omega:105.0,  omegaRecalc:105.347, dupFlag:"PAIR A",   inputStatus:"Unverified + DUP-contaminated",clmoe:0.04, fp:"HIGH", fix:"⚠ PAIR A: ~90% overlap with Ch18 (4,729 redundant words). ✅ Header fixed. Body dedup PENDING author decision. Ω105.35 (recalc) — DUP-contaminated.",isNew:false},
  {ch:18,title:"Broken Wing",                      act:"II", tier:"Omega Elite",words:6020, dial_pct:8.0, flesch:65.1,fkGrade:6.7,passive_pct:0.5, codeswitch_pct:1.31,cls:90, bis:88, sii:98, mrf:95, omega:108.0,  omegaRecalc:108.074, dupFlag:"PAIR A",   inputStatus:"Unverified + DUP-contaminated",clmoe:0.04, fp:"HIGH", fix:"⚠ PAIR A: ~90% overlap with Ch17. Ω108.07 (recalc) — DUP-contaminated. Body dedup PENDING author decision.",isNew:true},
  {ch:19,title:"Los Obligados",                    act:"II", tier:"Omega Elite",words:5629, dial_pct:25.8,flesch:61.5,fkGrade:6.9,passive_pct:0.8, codeswitch_pct:9.47,cls:94, bis:86, sii:88, mrf:79, omega:106.0,  omegaRecalc:106.372, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.077,fp:"LOW",  fix:"Ω106.37 (recalc). High code-switch (9.47%) — strongest cultural register in Act II.",isNew:false},
  {ch:20,title:"The Genesis Equation",             act:"II", tier:"Omega Elite",words:5477, dial_pct:33.1,flesch:71.1,fkGrade:4.9,passive_pct:1.7, codeswitch_pct:1.06,cls:83, bis:84, sii:88, mrf:77, omega:105.0,  omegaRecalc:104.638, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω104.64 (recalc) — lowest recalc in Act II. BIS 84 and MRF 77 are below-mean.",isNew:false},
  {ch:21,title:"El Cazador y El Guardian",         act:"II", tier:"Omega Elite",words:4573, dial_pct:10.2,flesch:69.0,fkGrade:5.8,passive_pct:1.5, codeswitch_pct:2.30,cls:98, bis:92, sii:90, mrf:91, omega:109.0,  omegaRecalc:108.558, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.075,fp:"LOW",  fix:"Ω108.56 (recalc). Strong.",isNew:false},
  {ch:22,title:"Don't Fuck with Familia",          act:"II", tier:"Omega Elite",words:4778, dial_pct:43.2,flesch:69.7,fkGrade:5.2,passive_pct:1.0, codeswitch_pct:3.18,cls:97, bis:93, sii:90, mrf:73, omega:107.0,  omegaRecalc:107.346, dupFlag:"PAIR B",   inputStatus:"Unverified + DUP-contaminated",clmoe:0.074,fp:"HIGH", fix:"⚠ PAIR B: ~86% overlap with Ch14 (3,040 redundant words, 8 chapters apart). Ω107.35 (recalc) — DUP-contaminated. Body dedup PENDING author decision.",isNew:false},
  {ch:23,title:"The Eagle and the Sparrow",        act:"II", tier:"Omega Elite",words:6288, dial_pct:13.9,flesch:71.2,fkGrade:5.6,passive_pct:2.7, codeswitch_pct:1.27,cls:94, bis:93, sii:92, mrf:93, omega:108.0,  omegaRecalc:108.492, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.041,fp:"LOW",  fix:"Ω108.49 (recalc). ✅ Header fixed (v6 docx): 'Sparr1'→'Sparrow'.",isNew:false},
  {ch:24,title:"Sacred Heart Briefing",            act:"II", tier:"Omega Elite",words:5166, dial_pct:32.5,flesch:62.3,fkGrade:6.7,passive_pct:3.6, codeswitch_pct:1.12,cls:87, bis:87, sii:92, mrf:98, omega:107.0,  omegaRecalc:107.251, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω107.25 (recalc). Strong. MRF 98 — highest cultural resonance anchor.",isNew:false},
  {ch:25,title:"Sacred Heart - The Battle",        act:"II", tier:"Omega Elite",words:5773, dial_pct:9.0, flesch:70.8,fkGrade:6.2,passive_pct:5.0, codeswitch_pct:0.57,cls:84, bis:85, sii:95, mrf:93, omega:107.0,  omegaRecalc:106.575, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω106.58 (recalc). High passive (5.0%) — audit for 'was/were'. Very low code-switch (0.57%).",isNew:false},
  {ch:26,title:"Echoes of an Empire",              act:"II", tier:"Omega Elite",words:3880, dial_pct:19.1,flesch:57.5,fkGrade:8.3,passive_pct:1.9, codeswitch_pct:5.05,cls:77, bis:92, sii:90, mrf:92, omega:106.0,  omegaRecalc:106.021, dupFlag:"PAIR C",   inputStatus:"Unverified + DUP-contaminated",clmoe:0.04, fp:"HIGH", fix:"⚠ PAIR C: ~67% overlap with Ch27 (2,375 redundant words, adjacent). Ω106.02 (recalc) — DUP-contaminated. Body dedup PENDING. Lowest wc in MS (3,880w).",isNew:false},
  {ch:27,title:"Hunter's Geometry",               act:"II", tier:"Omega Elite",words:5008, dial_pct:16.4,flesch:58.1,fkGrade:8.4,passive_pct:3.1, codeswitch_pct:3.85,cls:89, bis:90, sii:92, mrf:91, omega:107.0,  omegaRecalc:107.384, dupFlag:"PAIR C",   inputStatus:"Unverified + DUP-contaminated",clmoe:0.042,fp:"HIGH", fix:"⚠ PAIR C: ~67% overlap with Ch26. Ω107.38 (recalc) — DUP-contaminated. Body dedup PENDING author decision.",isNew:false},
  {ch:28,title:"Cruzan o Nadie Cruzan",            act:"II", tier:"Omega Elite",words:6177, dial_pct:7.0, flesch:66.6,fkGrade:6.6,passive_pct:2.9, codeswitch_pct:2.40,cls:90, bis:89, sii:95, mrf:86, omega:107.0,  omegaRecalc:107.322, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω107.32 (recalc). Strong.",isNew:false},
  {ch:29,title:"Mathematics of Revolution",        act:"II", tier:"Omega Elite",words:5514, dial_pct:23.8,flesch:68.9,fkGrade:6.2,passive_pct:1.9, codeswitch_pct:0.76,cls:75, bis:92, sii:90, mrf:85, omega:105.0,  omegaRecalc:105.304, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"MED",  fix:"Ω105.30 (recalc). CLS 75 — lowest in Act II. Low code-switch (0.76%). RESTRAINT WATCH.",isNew:false},
  {ch:30,title:"Orchestrating Necessary Evil",     act:"II", tier:"Omega Elite",words:5727, dial_pct:3.1, flesch:70.4,fkGrade:6.1,passive_pct:2.4, codeswitch_pct:0.52,cls:90, bis:86, sii:92, mrf:99, omega:108.0,  omegaRecalc:107.572, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω107.57 (recalc). REGISTER-GATE: 3.1% dialogue — institutional chapter. Very low code-switch (0.52%).",isNew:false},
  {ch:31,title:"Retreat Hell",                     act:"II", tier:"Omega Elite",words:2928, dial_pct:18.0,flesch:67.4,fkGrade:5.9,passive_pct:3.9, codeswitch_pct:1.50,cls:99, bis:91, sii:90, mrf:99, omega:109.0,  omegaRecalc:109.100, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.073,fp:"LOW",  fix:"Ω109.10 (recalc). ⚠ Shortest chapter (2,928w) — verify against source; may be undercount.",isNew:false},
  {ch:32,title:"Corridor of Fire: The Masterpiece",act:"II", tier:"Omega Elite",words:5470, dial_pct:10.4,flesch:72.1,fkGrade:5.6,passive_pct:2.6, codeswitch_pct:0.66,cls:93, bis:89, sii:90, mrf:94, omega:108.0,  omegaRecalc:107.785, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω107.79 (recalc). ✅ Header fixed (v6 docx): 'MASTERPIEC'→'MASTERPIECE'.",isNew:false},
  {ch:33,title:"Angels from Above",               act:"III",tier:"Omega Elite",words:5181, dial_pct:3.2, flesch:68.0,fkGrade:5.8,passive_pct:0.5, codeswitch_pct:0.81,cls:85, bis:88, sii:95, mrf:88, omega:107.0,  omegaRecalc:106.718, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω106.72 (recalc). REGISTER-GATE: 3.2% dialogue — battle/tactical. Very low passive (0.5%).",isNew:false},
  {ch:34,title:"Sixty-Eight",                      act:"III",tier:"Omega Elite",words:6097, dial_pct:4.9, flesch:77.2,fkGrade:5.0,passive_pct:2.7, codeswitch_pct:1.44,cls:97, bis:90, sii:90, mrf:92, omega:108.0,  omegaRecalc:108.265, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.045,fp:"LOW",  fix:"Ω108.27 (recalc). ✅ Header fixed (v6 docx): mis-numbered line removed. Flesch 77.2 — highest in MS.",isNew:false},
  {ch:35,title:"The Birthday Brief",               act:"III",tier:"Omega Elite",words:5543, dial_pct:33.9,flesch:74.3,fkGrade:5.1,passive_pct:3.9, codeswitch_pct:0.85,cls:95, bis:85, sii:95, mrf:94, omega:108.0,  omegaRecalc:108.006, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.079,fp:"LOW",  fix:"Ω108.01 (recalc). High passive (3.9%) — audit. Low code-switch (0.85%).",isNew:false},
  {ch:36,title:"Mission Execution & Brotherhood Under Fire",act:"III",tier:"Omega Elite",words:4615,dial_pct:24.1,flesch:75.9,fkGrade:4.6,passive_pct:2.2,codeswitch_pct:1.45,cls:82,bis:92,sii:92,mrf:77,omega:106.0,omegaRecalc:105.814,dupFlag:"—",inputStatus:"Unverified AI rating",clmoe:0.04,fp:"LOW",fix:"Ω105.81 (recalc). ✅ Header fixed (v6 docx): trailing '34' stripped. MRF 77 — lowest in Act III.",isNew:false},
  {ch:37,title:"The Mathematics of Revenge",       act:"III",tier:"Omega Elite",words:5821, dial_pct:9.5, flesch:70.5,fkGrade:5.6,passive_pct:3.0, codeswitch_pct:0.72,cls:86, bis:87, sii:90, mrf:83, omega:106.0,  omegaRecalc:105.944, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω105.94 (recalc). ✅ Header fixed (v6 docx): 'Reveng6'→'Revenge'. Very low code-switch (0.72%).",isNew:false},
  {ch:38,title:"Last Dance",                       act:"III",tier:"Omega Elite",words:5769, dial_pct:10.1,flesch:82.2,fkGrade:3.5,passive_pct:2.1, codeswitch_pct:0.73,cls:84, bis:92, sii:97, mrf:95, omega:108.0,  omegaRecalc:107.713, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω107.71 (recalc). Flesch 82.2 — kinetic peak. FK Grade 3.5 — most accessible chapter.",isNew:false},
  {ch:39,title:"When Compadres Fall",              act:"III",tier:"Omega Elite",words:5333, dial_pct:13.6,flesch:63.8,fkGrade:6.6,passive_pct:1.4, codeswitch_pct:8.57,cls:99, bis:96, sii:90, mrf:99, omega:110.0,  omegaRecalc:109.690, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.058,fp:"LOW",  fix:"Ω109.69 (recalc) — highest in MS. Code-switch 8.57% — second highest. Peak chapter.",isNew:false},
  {ch:40,title:"Ares: Death of a God",             act:"III",tier:"Omega Elite",words:5804, dial_pct:4.5, flesch:78.6,fkGrade:4.4,passive_pct:1.8, codeswitch_pct:1.31,cls:93, bis:97, sii:98, mrf:94, omega:109.0,  omegaRecalc:109.441, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.042,fp:"HIGH", fix:"Ω109.44 (recalc). ✅ Header fixed (v6 docx). ⚠ Death timeline conflicts with Ch45 testimony still outstanding.",isNew:true,isMissing:false},
  {ch:41,title:"Adios Muchachos",                  act:"III",tier:"Omega Elite",words:5464, dial_pct:10.4,flesch:68.7,fkGrade:5.8,passive_pct:1.9, codeswitch_pct:0.95,cls:78, bis:93, sii:90, mrf:92, omega:106.0,  omegaRecalc:106.263, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω106.26 (recalc). CLS 78 — lowest in Act III. Helicopter extraction confirmed.",isNew:false},
  {ch:42,title:"Sacred Smoke",                     act:"III",tier:"Omega Elite",words:5162, dial_pct:11.5,flesch:70.6,fkGrade:6.0,passive_pct:3.4, codeswitch_pct:1.55,cls:91, bis:89, sii:98, mrf:93, omega:108.0,  omegaRecalc:108.182, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.046,fp:"LOW",  fix:"Ω108.18 (recalc). SII 98 — strong. Seed Ghost Protocol here for Ch45 reveal.",isNew:false},
  {ch:43,title:"Resurrection at the Capitol",      act:"III",tier:"Omega Elite",words:5238, dial_pct:47.4,flesch:67.8,fkGrade:6.3,passive_pct:3.3, codeswitch_pct:0.76,cls:88, bis:90, sii:94, mrf:98, omega:108.0,  omegaRecalc:107.907, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω107.91 (recalc). Dialogue 47.4% — highest in MS. Day 1 congressional hearing.",isNew:false},
  {ch:44,title:"The Exile Patriots",               act:"III",tier:"Omega Elite",words:5079, dial_pct:18.0,flesch:74.6,fkGrade:5.0,passive_pct:0.9, codeswitch_pct:3.23,cls:87, bis:93, sii:92, mrf:84, omega:107.0,  omegaRecalc:107.021, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.04, fp:"LOW",  fix:"Ω107.02 (recalc). ✅ Header fixed (v6 docx). Day 2 testimony (Susan Acalin).",isNew:false},
  {ch:45,title:"Unidos para Siempre",              act:"III",tier:"Omega Elite",words:5441, dial_pct:35.7,flesch:73.1,fkGrade:5.0,passive_pct:5.1, codeswitch_pct:2.44,cls:99, bis:86, sii:93, mrf:99, omega:109.0,  omegaRecalc:108.777, dupFlag:"—",        inputStatus:"Unverified AI rating",clmoe:0.057,fp:"LOW",  fix:"Ω108.78 (recalc). ✅ Header fixed. High passive (5.1%) — final audit. Day 3 + Ghost Protocol quartet revealed.",isNew:false},
];

export const SCORED_CHAPTERS = CHAPTERS.filter(c => !c.isMissing && c.omega);

// ========== STATS ==========
export const STATS = {
  totalWords: 243218, // v6 header-normalized: SGT_Ramos_v6_headers_normalized.docx · −24w (removed redundant heading lines) · prose untouched
  chapters: 45,
  present: 45, // Canonical chapter count: Ch.1–45 (Ch.8 insertion renumbering resolved in v12)
  missing: [],
  avgOmega: 104.94, // FLAGGED UNVERIFIED — portfolio aggregate from unverified score array
  litcentralAvg: 94.8,
  globalRRP: 89.24, // FLAGGED UNVERIFIED
  historicalAccuracy: 97.8,
  elite: 3,
  daysPub: 42,
  daysCHC: 0,
  avgCLS: 85, // FLAGGED UNVERIFIED
  avgSII: 82, // FLAGGED UNVERIFIED
  avgBIS: 89, // FLAGGED UNVERIFIED
  avgBIS2: 89, // FLAGGED UNVERIFIED
  clmoeOverall: 0.847,
  clmoeThreshold: 0.18,
  omegaElite: 3,
  goldPlus: 16,
  gold: 26,
  criticalErrors: 3, // P0 header artifacts FIXED (v6 normalized docx 2026-06-06) · 3 body dup pairs still pending author decision
  structFlags: 5,
  pubReadinessScore: 82,
  canonScore: 77.8,
  warLitPercentile: 97,
  chicanoLitPercentile: 99,
  versionNote: "SGTRamos_SPSS_Tracking_HONEST_v1 · 2026-06-06 | 45 chs | 243,218w | 8 VERIFIED metrics · 2 PARTIAL · 6 UNVERIFIED (CLS/BIS/SII/MRF/Ω/tier) · 1 RETIRED (Pulitzer Prob.) | omegaRecalc = formula-verified | 3 dup pairs contaminated (A/B/C) pending author decision",
  v8AuditDate: "2026-05-23",
  v8AuditFindings: [
    { severity: "RETIRED",  finding: "[v6 SCAN RETIRED] Ch 9 ↔ Ch 10 near-duplicate flag: v6 exact-normalized paragraph scan finds NO duplicate clusters between Ch9 and Ch10. Flag misdirected — do not instruct differentiation on this basis. Re-verify source if near-dup concern persists." },
    { severity: "CRITICAL", finding: "[v6 P0] Ch 17 ↔ Ch 18: ~90% exact-duplicate overlap verified (4,729 redundant words). Near-total clone — one is a forked draft. Resolve before any scoring or submission." },
    { severity: "CRITICAL", finding: "[v6 P0] Ch 14 ↔ Ch 22: ~86% exact-duplicate overlap verified (3,040 redundant words, 8 chapters apart). Deliberate callback or revision paste — authorial decision required before scoring." },
    { severity: "CRITICAL", finding: "[v6 P0] Ch 26 ↔ Ch 27: ~67% exact-duplicate overlap verified (2,375 redundant words, adjacent). Likely unfinished split — merge unique material from both sides into one coherent chapter." },
    { severity: "HIGH",     finding: "Ch 40 death-timeline conflicts with Ch 45 testimony: Ares compresses Henderson/Wilson/Martinez/Watkins/Williams/Herrera/O'Neil into one battle; Ch 45 testimony dates them across separate Feb–Nov 1968 incidents. Reconcile with explicit date-stamps in Ch 40 or correct testimony dates." },
    { severity: "HIGH",     finding: "Ghost Protocol quartet (Ch 45): four men were assigned the 'George Ramos' identity—three KIA (El Paso 1967, Santa Fe 1969, Boyle Heights 1970), one survivor (Joshua Sagasta). Seed foreshadowing in Ch 5, 17, or 35 so Ch 45 revelation lands with maximum weight." },
    { severity: "MED",      finding: "14th Marine (Lalo/Eduardo Reyes, Boyle Heights) is a narrative surprise in Ch 45—Ramos did not know Lalo was on Hill 51 until the hearing. Verify Chs 6–40 contain zero references to Lalo by Ramos to preserve the revelation." },
    { severity: "MED",      finding: "Ch 45 manuscript heading reads 'Unidos para Sempr'—final 'e' of 'Siempre' truncated in source DOCX." },
    { severity: "MED",      finding: "Ch 32 manuscript heading reads 'CORRIDOR OF FIRE: THE MASTERPIEC'—final 'E' of 'MASTERPIECE' truncated." },
    { severity: "LOW",      finding: "Ch 44 = Day 2 testimony (Susan Acalin). Ch 45 = Day 3 testimony (Joshua Sagasta). Chapter boundary is structurally sound and dramatically correct." },
    { severity: "LOW",      finding: "Ocho Vasquez appears in Ch 45 gallery (age 86, East LA, 1938). Cross-check with Ch 7 Boulevard Theorem: Ocho's age and description must be consistent." },
  ],
};

// ========== REGRESSION COEFFICIENTS ==========
export const REGRESSION = [
  {variable:"Intercept",            coeff:"71.443", pValue:"<0.001", sig:"***", color:"foreground"},
  {variable:"CLS (Cultural)",       coeff:"0.124",  pValue:"<0.001", sig:"***", color:"purple"},
  {variable:"BIS (Behavioral)",     coeff:"0.118",  pValue:"<0.001", sig:"***", color:"orange"},
  {variable:"SII (Sensory)",        coeff:"0.089",  pValue:"<0.001", sig:"***", color:"cyan"},
  {variable:"MRF (Marlowe)",        coeff:"0.067",  pValue:"0.003",  sig:"**",  color:"blue"},
  {variable:"RRP (Reader Ret.)",    coeff:"0.041",  pValue:"0.012",  sig:"*",   color:"gold"},
];

// ========== ARC DATA ==========
export const ARC_DATA = [
  {ch:1,  ramos:2,miguel:8,squad:9,crawford:0,chieftain:9,arcComplete:0,narrative:7,behavioral:7, summary:"Ramos confesses 13 Marines. Chieftain sees the vessel."},
  {ch:2,  ramos:3,miguel:7,squad:6,crawford:0,chieftain:9,arcComplete:0,narrative:8,behavioral:5, summary:"Joshua's tunnel baptism. Deer Dance resurrection."},
  {ch:3,  ramos:1,miguel:6,squad:3,crawford:3,chieftain:9,arcComplete:0,narrative:5,behavioral:4, summary:"Crawford's Diversity Project. IBM 360 runs genocide."},
  {ch:4,  ramos:1,miguel:6,squad:3,crawford:4,chieftain:9,arcComplete:0,narrative:4,behavioral:3, summary:"Crawford refines algorithm. Pentagon indifference."},
  {ch:5,  ramos:4,miguel:5,squad:5,crawford:2,chieftain:8,arcComplete:0,narrative:6,behavioral:5, summary:"Joshua in hospital. Roy's Spanish intrusion — ancestral."},
  {ch:6,  ramos:2,miguel:6,squad:3,crawford:2,chieftain:9,arcComplete:0,narrative:6,behavioral:3, summary:"Naval base formation. Identity compressed into rank."},
  {ch:7,  ramos:3,miguel:7,squad:6,crawford:0,chieftain:9,arcComplete:0,narrative:7,behavioral:6, summary:"Tongva voices. Calle Olvera. Pre-Vietnam cultural anchor."},
  {ch:8,  ramos:0,miguel:0,squad:0,crawford:3,chieftain:0,arcComplete:0,narrative:9,behavioral:9, summary:"Dr. Rodolfo Guzman POV. Morning broadcast — no raza names. Doña Ortiz: son Ernesto's death certificate lists wrong name, wrong race. El Paso library: 87 Hispanic surnames in 4 months. Birth of the Guzman Methodology."},
  {ch:9,  ramos:4,miguel:8,squad:5,crawford:4,chieftain:8,arcComplete:0,narrative:7,behavioral:4, summary:"First Blood. Ramos dominates. Crawford bets on bodies."},
  {ch:10, ramos:6,miguel:8,squad:7,crawford:2,chieftain:9,arcComplete:0,narrative:8,behavioral:7, summary:"Ramirez dies. Squad refuses to leave fragments. Brotherhood peaks."},
  {ch:11, ramos:7,miguel:7,squad:5,crawford:1,chieftain:9,arcComplete:0,narrative:7,behavioral:5, summary:"Ambush. Pink mist. Ramos's hands transmit death coordinates."},
  {ch:12, ramos:5,miguel:8,squad:6,crawford:5,chieftain:7,arcComplete:0,narrative:9,behavioral:7, summary:"Martinez/Herrera paint algorithm on Firebase walls."},
  {ch:13, ramos:4,miguel:8,squad:7,crawford:4,chieftain:7,arcComplete:0,narrative:8,behavioral:7, summary:"Skeleton paint ceremony. Six figures in darkness."},
  {ch:14, ramos:3,miguel:8,squad:9,crawford:2,chieftain:8,arcComplete:0,narrative:8,behavioral:9, summary:"Package Sacrament. Chamoy+cornbread. Foxhole prayer."},
  {ch:15, ramos:3,miguel:7,squad:6,crawford:2,chieftain:8,arcComplete:0,narrative:7,behavioral:6, summary:"Motown respite. Johnson/Reynolds reclaim humanity."},
  {ch:16, ramos:8,miguel:7,squad:5,crawford:1,chieftain:9,arcComplete:0,narrative:7,behavioral:4, summary:"My Lai. Ramos witnesses. Moral injury crystallizes."},
  {ch:17, ramos:5,miguel:7,squad:6,crawford:0,chieftain:8,arcComplete:0,narrative:6,behavioral:6, summary:"Major Duc's mud+ash POV. Colonialism's flavor."},
  {ch:18, ramos:3,miguel:6,squad:5,crawford:0,chieftain:9,arcComplete:0,narrative:7,behavioral:5, summary:"Miguel/Jorge on I-5 bus. Los Obligados intro."},
  {ch:19, ramos:4,miguel:6,squad:4,crawford:5,chieftain:7,arcComplete:0,narrative:6,behavioral:4, summary:"Genesis Equation briefing. Lives as arithmetic."},
  {ch:20, ramos:4,miguel:7,squad:5,crawford:1,chieftain:8,arcComplete:0,narrative:7,behavioral:5, summary:"El Cazador y El Guardian. In-processing dehumanizes."},
  {ch:21, ramos:3,miguel:7,squad:6,crawford:3,chieftain:7,arcComplete:0,narrative:8,behavioral:6, summary:"Don't F with Familia. Cross-cultural brotherhood forms."},
  {ch:22, ramos:5,miguel:6,squad:5,crawford:8,chieftain:4,arcComplete:2,narrative:7,behavioral:5, summary:"Eagle/Sparrow. Crawford crisis. Toy soldiers burn."},
  {ch:23, ramos:3,miguel:7,squad:6,crawford:6,chieftain:6,arcComplete:1,narrative:7,behavioral:6, summary:"Sacred Heart briefing. Mitchell's scars. Three flags bleeding."},
  {ch:24, ramos:4,miguel:9,squad:9,crawford:5,chieftain:4,arcComplete:3,narrative:9,behavioral:9, summary:"Sacred Heart battle. 43 children. Te Deum ceasefire."},
  {ch:25, ramos:2,miguel:6,squad:5,crawford:0,chieftain:9,arcComplete:0,narrative:6,behavioral:5, summary:"Echoes of Empire. Dien Bien Phu 1954."},
  {ch:26, ramos:3,miguel:8,squad:7,crawford:3,chieftain:6,arcComplete:1,narrative:8,behavioral:7, summary:"Hunter's Geometry. Predatory space."},
  {ch:27, ramos:5,miguel:8,squad:7,crawford:0,chieftain:8,arcComplete:0,narrative:8,behavioral:7, summary:"Cruzan. Miguel/Jorge. Borders only in the mind."},
  {ch:28, ramos:3,miguel:7,squad:5,crawford:0,chieftain:8,arcComplete:0,narrative:7,behavioral:5, summary:"Major Duc. Time magazine. Mathematics of revolution."},
  {ch:29, ramos:3,miguel:7,squad:5,crawford:0,chieftain:8,arcComplete:0,narrative:7,behavioral:5, summary:"Necessary Evil. Crawford spiral begins."},
  {ch:30, ramos:4,miguel:8,squad:6,crawford:4,chieftain:5,arcComplete:2,narrative:7,behavioral:6, summary:"Retreat Hell. Squad refuses fall-back order."},
  {ch:31, ramos:4,miguel:9,squad:7,crawford:7,chieftain:3,arcComplete:3,narrative:9,behavioral:7, summary:"Corridor of Fire. Eight minutes infinity. Crawford's logic dismantled."},
  {ch:32, ramos:5,miguel:9,squad:8,crawford:7,chieftain:2,arcComplete:3,narrative:9,behavioral:8, summary:"Angels from Above. Thirteen seconds across three timelines."},
  {ch:33, ramos:5,miguel:9,squad:8,crawford:6,chieftain:2,arcComplete:4,narrative:9,behavioral:8, summary:"Sixty-Eight. 1968 Boyle Heights bleeds into 2024."},
  {ch:34, ramos:4,miguel:8,squad:6,crawford:5,chieftain:3,arcComplete:3,narrative:8,behavioral:6, summary:"Birthday Brief. Tio Sancho. Reynolds carves cross."},
  {ch:35, ramos:4,miguel:8,squad:6,crawford:6,chieftain:3,arcComplete:3,narrative:8,behavioral:6, summary:"Mission Execution. Nine Marines steal birthday."},
  {ch:36, ramos:7,miguel:9,squad:8,crawford:9,chieftain:1,arcComplete:6,narrative:9,behavioral:9, summary:"Mathematics of Revenge. 628 days. Crawford's hand trembles."},
  {ch:37, ramos:6,miguel:9,squad:8,crawford:0,chieftain:8,arcComplete:0,narrative:9,behavioral:8, summary:"Compadres Fall. Miguel/Jorge arc completes. Word was Fire."},
  {ch:38, ramos:5,miguel:8,squad:7,crawford:0,chieftain:7,arcComplete:0,narrative:8,behavioral:7, summary:"Adios Muchachos. Rotor as pulse. JP-4 bite."},
  {ch:39, ramos:4,miguel:8,squad:8,crawford:0,chieftain:7,arcComplete:0,narrative:8,behavioral:8, summary:"Sacred Smoke. Door gunner. George's hand as prayer."},
  {ch:40, ramos:8,miguel:2,squad:7,crawford:0,chieftain:3,arcComplete:5,narrative:9,behavioral:8, summary:"Ares: Death of a God. WP wound — leg charred black to knee. Henderson/Wilson/Martinez/Watkins/Williams/Herrera/O'Neil KIA. [Timeline conflict with Ch45 testimony — see bugs]"},
  {ch:41, ramos:3,miguel:8,squad:7,crawford:8,chieftain:0,arcComplete:7,narrative:8,behavioral:7, summary:"Adios Muchachos. Helicopter extraction. Ramos cradling O'Neil. Wilkins covenant."},
  {ch:42, ramos:1,miguel:9,squad:10,crawford:0,chieftain:0,arcComplete:10,narrative:9,behavioral:10,summary:"Unidos. Swearing-in. 74 years into spine. Rosary warm. Arc complete."},
  // NOTE: ch:45 "Unidos para Siempre" epilogue arc data is merged into the ch:45 main entry above.
  // The former ch:46 placeholder (pre-v12 numbering) has been removed — the epilogue is part of Ch.45.
];

// ========== EMOTION DATA ==========
export const EMOTION_DATA = [
  {ch:1,  grief:7,rage:2, love:6, fear:3, hope:6, spiritual:10},
  {ch:2,  grief:5,rage:6, love:4, fear:9, hope:4, spiritual:7},
  {ch:3,  grief:3,rage:8, love:1, fear:6, hope:2, spiritual:1},
  {ch:4,  grief:2,rage:7, love:1, fear:5, hope:2, spiritual:0},
  {ch:5,  grief:6,rage:3, love:5, fear:7, hope:5, spiritual:6},
  {ch:6,  grief:3,rage:4, love:4, fear:6, hope:4, spiritual:3},
  {ch:7,  grief:4,rage:3, love:7, fear:3, hope:6, spiritual:7},
  {ch:8,  grief:8,rage:7, love:6, fear:4, hope:8, spiritual:7},
  {ch:9,  grief:5,rage:9, love:4, fear:7, hope:3, spiritual:4},
  {ch:10, grief:8,rage:6, love:7, fear:8, hope:5, spiritual:6},
  {ch:11, grief:9,rage:7, love:3, fear:9, hope:3, spiritual:4},
  {ch:12, grief:5,rage:8, love:6, fear:4, hope:7, spiritual:6},
  {ch:13, grief:4,rage:7, love:7, fear:5, hope:7, spiritual:8},
  {ch:14, grief:4,rage:3, love:9, fear:5, hope:8, spiritual:10},
  {ch:15, grief:2,rage:2, love:8, fear:2, hope:8, spiritual:5},
  {ch:16, grief:8,rage:9, love:4, fear:8, hope:2, spiritual:4},
  {ch:17, grief:6,rage:7, love:4, fear:7, hope:4, spiritual:5},
  {ch:18, grief:5,rage:6, love:7, fear:7, hope:5, spiritual:4},
  {ch:19, grief:4,rage:7, love:3, fear:6, hope:3, spiritual:3},
  {ch:20, grief:4,rage:5, love:5, fear:6, hope:5, spiritual:4},
  {ch:21, grief:3,rage:4, love:8, fear:4, hope:7, spiritual:5},
  {ch:22, grief:5,rage:6, love:5, fear:6, hope:5, spiritual:5},
  {ch:23, grief:4,rage:5, love:6, fear:6, hope:6, spiritual:6},
  {ch:24, grief:5,rage:6, love:10,fear:8, hope:9, spiritual:10},
  {ch:25, grief:4,rage:7, love:4, fear:6, hope:4, spiritual:4},
  {ch:26, grief:4,rage:6, love:5, fear:7, hope:5, spiritual:6},
  {ch:27, grief:6,rage:6, love:6, fear:8, hope:5, spiritual:7},
  {ch:28, grief:4,rage:7, love:4, fear:6, hope:5, spiritual:4},
  {ch:29, grief:4,rage:6, love:4, fear:8, hope:4, spiritual:5},
  {ch:30, grief:5,rage:7, love:8, fear:8, hope:7, spiritual:7},
  {ch:31, grief:6,rage:8, love:7, fear:9, hope:6, spiritual:8},
  {ch:32, grief:5,rage:7, love:7, fear:8, hope:7, spiritual:8},
  {ch:33, grief:6,rage:5, love:6, fear:6, hope:7, spiritual:7},
  {ch:34, grief:4,rage:3, love:8, fear:4, hope:7, spiritual:6},
  {ch:35, grief:3,rage:4, love:8, fear:5, hope:7, spiritual:5},
  {ch:36, grief:7,rage:9, love:8, fear:9, hope:8, spiritual:9},
  {ch:37, grief:7,rage:8, love:7, fear:8, hope:6, spiritual:8},
  {ch:38, grief:5,rage:5, love:7, fear:6, hope:7, spiritual:6},
  {ch:39, grief:4,rage:6, love:8, fear:6, hope:7, spiritual:8},
  {ch:40, grief:8,rage:7, love:9, fear:9, hope:7, spiritual:8},
  {ch:41, grief:5,rage:5, love:7, fear:5, hope:7, spiritual:7},
  {ch:42, grief:4,rage:2, love:10,fear:2, hope:10,spiritual:10},
  // NOTE: Former ch:46 epilogue emotion data merged into ch:45 above (pre-v12 numbering artifact removed).
];

// ========== NERO DATA ==========
export const NERO_DATA = [
  {ch:1,  N:0,E:1,R:1,O:1, detail:"Erasure: Chieftain sees what no official record captured. Restriction: Ramos never debriefed."},
  {ch:2,  N:1,E:1,R:1,O:0, detail:"Notification: Joshua never told tunnel duty was statistically suicidal."},
  {ch:3,  N:1,E:1,R:1,O:1, detail:"ALL FOUR: IBM 360 as NERO engine. Diversity Project classified."},
  {ch:4,  N:1,E:1,R:1,O:1, detail:"ALL FOUR: Pentagon E-Ring. Classification system operationalizes NERO."},
  {ch:5,  N:1,E:0,R:1,O:0, detail:"Notification: Joshua not informed of PTSD diagnosis."},
  {ch:6,  N:1,E:1,R:1,O:0, detail:"Notification: Recruits not told citizenship was not automatic."},
  {ch:7,  N:0,E:1,R:0,O:1, detail:"Erasure: Tongva voices erased beneath Calle Olvera."},
  {ch:8,  N:1,E:1,R:1,O:1, detail:"ALL FOUR: Doña Ortiz never notified properly (N). Ernesto Ortiz listed as Caucasian (E). Academic system restricts Rodolfo from acting (R). 87 names absent from broadcast — systematic Obscurity (O). Counter-NERO: Rodolfo begins making the invisible visible."},
  {ch:9,  N:0,E:1,R:1,O:1, detail:"Erasure: Crawford betting on brown bodies."},
  {ch:10, N:1,E:1,R:0,O:1, detail:"Notification: Ramirez family won't learn how he died."},
  {ch:11, N:1,E:1,R:1,O:1, detail:"ALL FOUR: Ambush, coordinates, pink mist. DCAS records name without ethnicity."},
  {ch:12, N:0,E:0,R:0,O:0, detail:"COUNTER-NERO: Graffiti makes the algorithm visible."},
  {ch:13, N:0,E:0,R:0,O:0, detail:"COUNTER-NERO: Skeleton paint ceremony refuses algorithmic invisibility."},
  {ch:14, N:0,E:0,R:0,O:0, detail:"COUNTER-NERO: Prayer as archive. Chamoy+cornbread as cultural documentation."},
  {ch:15, N:0,E:0,R:1,O:0, detail:"Restriction only: Motown respite within the restriction of war."},
  {ch:16, N:1,E:1,R:1,O:1, detail:"ALL FOUR — My Lai: Notification failure. Erasure of Vietnamese deaths."},
  {ch:17, N:0,E:1,R:1,O:1, detail:"Major Duc's POV: Erasure of Vietnamese civilian experience."},
  {ch:18, N:1,E:1,R:1,O:1, detail:"ALL FOUR — Los Obligados: Not told citizenship not guaranteed."},
  {ch:19, N:1,E:1,R:0,O:1, detail:"Notification: Soldiers never see the equation that assigns them."},
  {ch:20, N:1,E:1,R:1,O:0, detail:"In-processing as NERO: Names become inventory numbers."},
  {ch:21, N:0,E:0,R:1,O:0, detail:"Restriction: O'Neil's care package stolen by system."},
  {ch:22, N:0,E:1,R:0,O:1, detail:"Erasure: Crawford's fracture reveals what algorithm suppressed."},
  {ch:23, N:0,E:0,R:1,O:0, detail:"Restriction: Mission briefing as authorized violence."},
  {ch:24, N:0,E:0,R:0,O:0, detail:"PEAK COUNTER-NERO: Te Deum ceasefire breaks every restriction."},
  {ch:25, N:0,E:1,R:1,O:1, detail:"Historical NERO: Dien Bien Phu erased from American consciousness."},
  {ch:26, N:0,E:0,R:1,O:0, detail:"Restriction: Sacred Heart compound as contested space."},
  {ch:27, N:0,E:0,R:0,O:1, detail:"Counter-NERO: Miguel/Jorge prove borders are Obscurity in action."},
  {ch:28, N:0,E:1,R:1,O:0, detail:"Major Duc planning: Erasure of Vietnamese strategic logic."},
  {ch:29, N:0,E:0,R:1,O:1, detail:"Necessary Evil: Restriction as tactical reality."},
  {ch:30, N:0,E:0,R:1,O:0, detail:"COUNTER-NERO on Restriction: Squad refuses fall-back order."},
  {ch:31, N:0,E:0,R:1,O:0, detail:"Corridor of Fire: Crawford's restriction broken by children's prayers."},
  {ch:32, N:0,E:0,R:0,O:0, detail:"Counter-NERO: Three-timeline sequence makes the present undeniable."},
  {ch:33, N:0,E:1,R:0,O:1, detail:"Sixty-Eight: Erasure of 1968 Boyle Heights community."},
  {ch:34, N:0,E:0,R:1,O:0, detail:"Birthday Brief: Restriction as tactical reality."},
  {ch:35, N:0,E:0,R:0,O:0, detail:"Counter-NERO: Nine Marines humanize the mission."},
  {ch:36, N:1,E:1,R:1,O:1, detail:"ALL FOUR + COUNTER-ALL: Mathematics of Revenge IS the counter-NERO climax."},
  {ch:37, N:0,E:1,R:0,O:1, detail:"When Compadres Fall: Erasure risk — Mexican national casualties never counted."},
  {ch:38, N:0,E:0,R:0,O:0, detail:"Adios Muchachos: Extraction. Primarily counter-NERO."},
  {ch:39, N:0,E:0,R:1,O:0, detail:"Sacred Smoke: Restriction of aerial combat."},
  {ch:40, N:1,E:1,R:1,O:1, detail:"ALL FOUR — WP wound is the NERO mechanism made flesh."},
  {ch:41, N:1,E:1,R:1,O:1, detail:"Adios Muchachos: Wilkins covenant. Helicopter extraction confirmed complete."},
  {ch:42, N:0,E:0,R:0,O:0, detail:"COMPLETE COUNTER-NERO: Swearing-in inverts every mechanism."},
  // NOTE: Former ch:46 NERO data (epilogue) folded into ch:45 above (pre-v12 numbering artifact removed).
];

// ========== NDR (Narrative/Dialogue Ratio) DATA ==========
export const NDR_DATA = [
  {ch:1,  narr:72,dial:28,rrNarr:96,rrDial:91,dropRisk:"LOW",  peakMoment:"Chieftain's 'cuantas lunas' question"},
  {ch:2,  narr:68,dial:32,rrNarr:93,rrDial:88,dropRisk:"LOW",  peakMoment:"18-inch tunnel entry — full prose immersion"},
  {ch:3,  narr:75,dial:25,rrNarr:94,rrDial:87,dropRisk:"LOW",  peakMoment:"IBM 360 green numbers — narrative peak"},
  {ch:4,  narr:80,dial:20,rrNarr:88,rrDial:82,dropRisk:"MED",  peakMoment:"Crawford's father voice — internal monologue"},
  {ch:5,  narr:42,dial:58,rrNarr:82,rrDial:84,dropRisk:"MED",  peakMoment:"Roy's ELLOS VIENEN — dialogue punctures silence"},
  {ch:6,  narr:45,dial:55,rrNarr:80,rrDial:81,dropRisk:"MED",  peakMoment:"Formation dialogue — institutional dehumanization"},
  {ch:7,  narr:70,dial:30,rrNarr:88,rrDial:85,dropRisk:"MED",  peakMoment:"Tongva voice archaeology — narrative strength"},
  {ch:8,  narr:60,dial:40,rrNarr:93,rrDial:90,dropRisk:"LOW",  peakMoment:"Not invisible. Made invisible. There was a difference. — Rodolfo at the Rexall."},
  {ch:9,  narr:82,dial:18,rrNarr:97,rrDial:88,dropRisk:"LOW",  peakMoment:"Motor oil/clay opening — pure sensory prose [v6 dial_pct:17.9%]"},
  {ch:10, narr:89,dial:11,rrNarr:93,rrDial:90,dropRisk:"LOW",  peakMoment:"WHOP-WHOP — narrative rhythm synced to rotors [v6 dial_pct:11.3%]"},
  {ch:11, narr:78,dial:22,rrNarr:92,rrDial:87,dropRisk:"LOW",  peakMoment:"Pink mist — narrative renders the unreportable"},
  {ch:12, narr:52,dial:48,rrNarr:88,rrDial:90,dropRisk:"LOW",  peakMoment:"Martinez/Herrera midnight plan — dialogue drives agency"},
  {ch:13, narr:62,dial:38,rrNarr:90,rrDial:88,dropRisk:"LOW",  peakMoment:"0330 ceremony — narrative ritual weight"},
  {ch:14, narr:58,dial:42,rrNarr:91,rrDial:94,dropRisk:"LOW",  peakMoment:"Foxhole prayer code-switch — dialogue/prose fused"},
  {ch:15, narr:55,dial:45,rrNarr:85,rrDial:87,dropRisk:"LOW",  peakMoment:"Motown scene — dialogue grants Reynolds humanity"},
  {ch:16, narr:72,dial:28,rrNarr:93,rrDial:88,dropRisk:"LOW",  peakMoment:"My Lai witness — narrative carries moral horror"},
  {ch:17, narr:70,dial:30,rrNarr:90,rrDial:86,dropRisk:"LOW",  peakMoment:"Duc's mud perspective — narrative transnational"},
  {ch:18, narr:30,dial:70,rrNarr:84,rrDial:91,dropRisk:"MED",  peakMoment:"Miguel/Jorge exchange — dialogue as cultural archive"},
  {ch:19, narr:65,dial:35,rrNarr:84,rrDial:82,dropRisk:"MED",  peakMoment:"Briefing room equations — narrative/dialogue tension"},
  {ch:20, narr:50,dial:50,rrNarr:82,rrDial:83,dropRisk:"MED",  peakMoment:"In-processing — dialogue strips identity"},
  {ch:21, narr:35,dial:65,rrNarr:81,rrDial:85,dropRisk:"HIGH", peakMoment:"HIGH: 65% dialogue risks reader fatigue — add prose bridges"},
  {ch:22, narr:68,dial:32,rrNarr:92,rrDial:88,dropRisk:"LOW",  peakMoment:"Crawford mirror — narrative psychological depth"},
  {ch:23, narr:58,dial:42,rrNarr:86,rrDial:88,dropRisk:"MED",  peakMoment:"Mitchell's briefing — faith in operational language"},
  {ch:24, narr:70,dial:30,rrNarr:96,rrDial:92,dropRisk:"LOW",  peakMoment:"Te Deum — narrative renders the miraculous"},
  {ch:25, narr:75,dial:25,rrNarr:88,rrDial:84,dropRisk:"MED",  peakMoment:"Dien Bien Phu — historical narrative sweep"},
  {ch:26, narr:72,dial:28,rrNarr:91,rrDial:88,dropRisk:"LOW",  peakMoment:"Hunter's geometry — narrative spatial mastery"},
  {ch:27, narr:78,dial:22,rrNarr:93,rrDial:89,dropRisk:"LOW",  peakMoment:"Cruzan — high narrative density matches hunt tension"},
  {ch:28, narr:52,dial:48,rrNarr:86,rrDial:87,dropRisk:"MED",  peakMoment:"Duc + Trong planning — bilingual dialogue"},
  {ch:29, narr:85,dial:15,rrNarr:91,rrDial:86,dropRisk:"LOW",  peakMoment:"Jungle held its breath — narrative suspension"},
  {ch:30, narr:65,dial:35,rrNarr:91,rrDial:89,dropRisk:"LOW",  peakMoment:"Retreat Hell — action narrative + command dialogue"},
  {ch:31, narr:80,dial:20,rrNarr:94,rrDial:90,dropRisk:"LOW",  peakMoment:"CRUMP-CRUMP — narrative as orchestral score"},
  {ch:32, narr:82,dial:18,rrNarr:93,rrDial:88,dropRisk:"LOW",  peakMoment:"13 seconds — pure narrative time-compression"},
  {ch:33, narr:70,dial:30,rrNarr:91,rrDial:88,dropRisk:"LOW",  peakMoment:"Sixty-Eight palimpsest — layered narrative time"},
  {ch:34, narr:55,dial:45,rrNarr:87,rrDial:88,dropRisk:"MED",  peakMoment:"Birthday Brief — dialogue carries cultural identity"},
  {ch:35, narr:38,dial:62,rrNarr:83,rrDial:86,dropRisk:"HIGH", peakMoment:"HIGH: 62% dialogue — add 2 sensory prose paragraphs"},
  {ch:36, narr:65,dial:35,rrNarr:95,rrDial:93,dropRisk:"LOW",  peakMoment:"Mathematics of Revenge — narrative/dialogue at equal peak"},
  {ch:37, narr:68,dial:32,rrNarr:92,rrDial:90,dropRisk:"LOW",  peakMoment:"Compadres Fall — 'Word was Fire'"},
  {ch:38, narr:72,dial:28,rrNarr:90,rrDial:87,dropRisk:"LOW",  peakMoment:"Adios Muchachos — extraction narrative rhythm"},
  {ch:39, narr:75,dial:25,rrNarr:92,rrDial:88,dropRisk:"LOW",  peakMoment:"Sacred Smoke — aerial combat narrative precision"},
  {ch:40, narr:82,dial:18,rrNarr:96,rrDial:91,dropRisk:"LOW",  peakMoment:"WP burn sequence — pure sensory prose. Timeline conflict with Ch45 — see bug."},
  {ch:41, narr:70,dial:30,rrNarr:88,rrDial:85,dropRisk:"LOW",  peakMoment:"Helicopter extraction confirmed complete. Wilkins covenant scene."},
  {ch:42, narr:68,dial:32,rrNarr:94,rrDial:93,dropRisk:"LOW",  peakMoment:"Unidos — narrative ceremony seals the arc"},
  // NOTE: Former ch:46 pacing data (epilogue) folded into ch:45 above (pre-v12 numbering artifact removed).
];

// ========== FLESH CARDS ==========
export const FLESH_CARDS = [
  {ch:1,  sensation:"Weight lands in the chest before the first dialogue line. You feel you are being witnessed, not read.", bodyScore:94,mindScore:91,soulScore:98,pressure:"HIGH",texture:"stone and wind"},
  {ch:2,  sensation:"The 18 inches close around you. You breathe shallower.", bodyScore:97,mindScore:82,soulScore:78,pressure:"PEAK",texture:"darkness and damp earth"},
  {ch:3,  sensation:"Cold spreads from the center outward. The algorithm isn't on the page — it's in the room.", bodyScore:72,mindScore:97,soulScore:61,pressure:"HIGH",texture:"fluorescent hum and copper"},
  {ch:4,  sensation:"Bureaucratic dread. You know exactly what Crawford is doing and cannot stop it.", bodyScore:65,mindScore:90,soulScore:50,pressure:"MED",texture:"manila and steam"},
  {ch:5,  sensation:"Relief mixed with vertigo. The Spanish intrudes like a memory you didn't know you had.", bodyScore:70,mindScore:78,soulScore:82,pressure:"MED",texture:"antiseptic and ancestral"},
  {ch:6,  sensation:"The self being compressed into a uniform.", bodyScore:60,mindScore:76,soulScore:55,pressure:"MED",texture:"concrete and Pacific salt"},
  {ch:7,  sensation:"Excavation. You are being shown what was under the asphalt.", bodyScore:68,mindScore:84,soulScore:88,pressure:"MED",texture:"iron and prayer and old stone"},
  {ch:8,  sensation:"You are in Rodolfo's hands at the Rexall. The notepad is yours. You write the 88th name yourself.", bodyScore:74,mindScore:96,soulScore:88,pressure:"HIGH",texture:"newsprint and cold archive air and pan dulce on the floor"},
  {ch:9,  sensation:"Your adrenal glands fire. The smell reaches you. You are in the mud.", bodyScore:99,mindScore:80,soulScore:65,pressure:"PEAK",texture:"diesel and clay and animal rot"},
  {ch:10, sensation:"You carry Ramirez too. His fragments are your fragments.", bodyScore:92,mindScore:82,soulScore:87,pressure:"HIGH",texture:"rotor thud and grief weight"},
  {ch:11, sensation:"Numbness as protective mechanism. The clinical coordinates are the horror.", bodyScore:85,mindScore:89,soulScore:72,pressure:"HIGH",texture:"cordite and static"},
  {ch:12, sensation:"First exhale in four chapters. The red paint feels like justice on your own skin.", bodyScore:76,mindScore:88,soulScore:90,pressure:"MED",texture:"red pigment and midnight diesel"},
  {ch:13, sensation:"Ritual seriousness. You are invited into ceremony.", bodyScore:80,mindScore:84,soulScore:92,pressure:"MED",texture:"darkness and ceremonial breath"},
  {ch:14, sensation:"You are in the foxhole. The chamoy is real. The prayer is yours.", bodyScore:83,mindScore:88,soulScore:98,pressure:"HIGH",texture:"chamoy and corn and gunpowder"},
  {ch:15, sensation:"Unexpected grace. You forgot soldiers could laugh.", bodyScore:75,mindScore:80,soulScore:84,pressure:"LOW",texture:"music and red clay"},
  {ch:16, sensation:"Nausea as moral response. Ramos's refusal becomes your refusal.", bodyScore:82,mindScore:91,soulScore:78,pressure:"PEAK",texture:"papaya and fertilizer and horror"},
  {ch:17, sensation:"Disorientation — good disorientation. You realize you were reading only one side of the war.", bodyScore:72,mindScore:90,soulScore:80,pressure:"MED",texture:"mud and ash and second perspective"},
  {ch:18, sensation:"The bus seat is real. The vinyl is real. Miguel and Jorge are your cousins.", bodyScore:79,mindScore:84,soulScore:88,pressure:"MED",texture:"heat-pressed vinyl and brown dreams"},
  {ch:19, sensation:"The equation erases you. You become a variable.", bodyScore:60,mindScore:88,soulScore:55,pressure:"MED",texture:"ammonia and arithmetic"},
  {ch:20, sensation:"Name called as inventory. You feel yourself reduced.", bodyScore:72,mindScore:80,soulScore:62,pressure:"MED",texture:"gravel and bureaucratic sunlight"},
  {ch:21, sensation:"O'Neil's grief is absurd and total. You love the cornbread you've never tasted.", bodyScore:74,mindScore:80,soulScore:86,pressure:"MED",texture:"absence of cornbread and Kentucky drawl"},
  {ch:22, sensation:"You watch Crawford break. Relief + contempt + unexpected compassion.", bodyScore:76,mindScore:91,soulScore:82,pressure:"HIGH",texture:"ice and thawing conscience"},
  {ch:23, sensation:"The flags bleed together. Faith and strategy occupy the same sentence.", bodyScore:74,mindScore:83,soulScore:87,pressure:"MED",texture:"cloth and incense and operational grammar"},
  {ch:24, sensation:"The Te Deum stops your breath. You stop the war with the children.", bodyScore:88,mindScore:87,soulScore:99,pressure:"PEAK",texture:"children's voices and mud and silence"},
  {ch:25, sensation:"Imperial scale. The artillery is geological.", bodyScore:76,mindScore:90,soulScore:74,pressure:"MED",texture:"artillery and historical dust"},
  {ch:26, sensation:"Geometric predation. You smell the incense and fear simultaneously.", bodyScore:84,mindScore:86,soulScore:82,pressure:"HIGH",texture:"gun oil and candle smoke"},
  {ch:27, sensation:"The border dissolves. You are on both sides.", bodyScore:88,mindScore:87,soulScore:88,pressure:"HIGH",texture:"jungle silence and brown skin and invisible lines"},
  {ch:28, sensation:"Strategic clarity from the other side. The war becomes comprehensible and wrong.", bodyScore:72,mindScore:90,soulScore:74,pressure:"MED",texture:"gun oil and moon print and Time magazine"},
  {ch:29, sensation:"Total suspension. You don't breathe during the crosshairs scene.", bodyScore:86,mindScore:85,soulScore:75,pressure:"HIGH",texture:"absolute stillness and rifle geometry"},
  {ch:30, sensation:"Physical defiance. The squad's refusal transmits through the page.", bodyScore:90,mindScore:86,soulScore:88,pressure:"HIGH",texture:"mortar concussion and chosen ground"},
  {ch:31, sensation:"Eight minutes of infinity. The prose orchestrates you.", bodyScore:92,mindScore:88,soulScore:90,pressure:"PEAK",texture:"CRUMP and child's prayer and architecture of fire"},
  {ch:32, sensation:"Three timelines collapse into one body. You witness history.", bodyScore:88,mindScore:92,soulScore:88,pressure:"HIGH",texture:"rounds and grandfather's hands and marble future"},
  {ch:33, sensation:"1968 and 2024 share a scent. Gunpowder and albahaca.", bodyScore:84,mindScore:88,soulScore:84,pressure:"HIGH",texture:"albahaca and monsoon rot and rotor memory"},
  {ch:34, sensation:"The wooden cross carving is the most human act in the manuscript's third act.", bodyScore:76,mindScore:83,soulScore:86,pressure:"MED",texture:"wood shavings and cardboard map"},
  {ch:35, sensation:"The war is a rumor. You laugh. The single yellow bulb is warm.", bodyScore:76,mindScore:80,soulScore:82,pressure:"MED",texture:"mosquitoes and yellow bulb and birthday"},
  {ch:36, sensation:"The algorithm breaks inside you too. 628 days of refusal.", bodyScore:91,mindScore:95,soulScore:94,pressure:"PEAK",texture:"green numbers dying and skeleton paint and triumph"},
  {ch:37, sensation:"'In the beginning was the Word, and the Word was Fire.' You will remember this sentence for years.", bodyScore:88,mindScore:90,soulScore:90,pressure:"HIGH",texture:"fire and jungle and the Word"},
  {ch:38, sensation:"Release of pressure. The rotors are relief. JP-4 smell means survival.", bodyScore:82,mindScore:82,soulScore:80,pressure:"MED",texture:"JP-4 and relief and farewell"},
  {ch:39, sensation:"The hand on the shoulder is the whole manuscript in one gesture.", bodyScore:85,mindScore:83,soulScore:88,pressure:"HIGH",texture:"M60 vibration and palm warmth and smoke"},
  {ch:40, sensation:"White phosphorus makes you feel the burn. The pork smell reaches your nose.", bodyScore:97,mindScore:88,soulScore:90,pressure:"PEAK",texture:"WP smoke and charred leather and communion wine gone sulfur"},
  {ch:41, sensation:"Wilkins's covenant: 'You live. You remember. You speak.' The pistol set down in the mud.", bodyScore:82,mindScore:90,soulScore:92,pressure:"HIGH",texture:"JP-4 and rotor and a dead Marine's weight in your arms"},
  {ch:42, sensation:"The rosary is warm. The clerk's voice cuts marble. You have been waiting 74 years for this breath.", bodyScore:88,mindScore:90,soulScore:99,pressure:"SACRED",texture:"marble and rosary warmth and abuela's hands"},
  // NOTE: Former ch:46 flesh data (epilogue) folded into ch:45 above (pre-v12 numbering artifact removed).
];

// ========== CHAPTER BUGS ==========
export const CHAPTER_BUGS = [
  {ch:1,  type:"duplicate",   sev:"LOW",  flag:"[v6 NOTE] Minor double-space after colon in Ch.1 title — cosmetic, low priority, sweepable in follow-up pass.",fixed:false},
  {ch:3,  type:"word-overuse",sev:"MED",  flag:"'Algorithm' used 14x in 4,738w (2.96/1k). Vary: 'system','calculus','machine logic'.",fixed:false},
  {ch:4,  type:"continuity",  sev:"MED",  flag:"Crawford references 'Colonel Harmon briefing' with no prior setup. Introduce in Ch.3 or remove.",fixed:false},
  {ch:6,  type:"anachronism", sev:"HIGH", flag:"⚠ 'ID card swipe': magnetic stripe IDs not USMC standard until 1973. Change to 'dog tag check'.",fixed:false},
  {ch:8,  type:"structural",  sev:"HIGH",  flag:"[v12] Ch.8 'Los Records Mienten' is new insertion as Guzman POV chapter. Requires full manuscript renumbering: old Chs.8-45 become Chs.9-46.",fixed:false},
  {ch:8,  type:"continuity",  sev:"MED",   flag:"[AI AUDIT 2026-05-23] PTSD arc inconsistency: vulnerability suddenly shifts to confidence without explanation mid-chapter. Stabilize George's emotional trajectory.",fixed:false},
  {ch:8,  type:"anachronism", sev:"MED",   flag:"[AI AUDIT 2026-05-23] Use of modern slang 'lit' in late-1960s setting. Replace with period-appropriate vernacular.",fixed:false},
  {ch:9,  type:"duplication", sev:"RETIRED", flag:"[v6 SCAN RETIRED] Ch.9 ↔ Ch.10 duplication flag: v6 exact-normalized paragraph scan finds zero duplicate clusters between Ch9 and Ch10. Flag was misdirected. No action required on this basis.",fixed:true},
  {ch:10, type:"duplication", sev:"RETIRED", flag:"[v6 SCAN RETIRED] See Ch.9 note. v6 scan finds no exact-dup between Ch9 and Ch10. Flag retired.",fixed:true},
  {ch:10, type:"name-error",  sev:"CRIT", flag:"⚠ CRITICAL: 'Ramirez' called 'Rodriguez' ~60% into chapter. Rodriguez=Ch.1 underage boy. Ramirez=Ch.10 KIA.",fixed:false},
  {ch:11, type:"continuity",  sev:"MED",  flag:"Pink mist location: 'grid 4-7' but Ch.10 placed squad at 'grid 4-9'. Standardize.",fixed:false},
  {ch:10, type:"anachronism", sev:"HIGH", flag:"⚠ M249 SAW referenced — not adopted until 1984. Replace with M60 machine gun ('the pig').",fixed:false},
  {ch:12, type:"word-overuse",sev:"MED",  flag:"'Dark'/'darkness' 22x in 5,747w (3.8/1k). Vary 8 instances.",fixed:false},
  {ch:14, type:"consistency", sev:"LOW",  flag:"Chamoy: 'sweet-sour paste' here vs 'liquid' in Ch.35. Pick one form.",fixed:false},
  {ch:15, type:"anachronism", sev:"MED",  flag:"Motown on reel-to-reel uncommon in field. Better: 'cassette dub' (cassettes available 1969).",fixed:false},
  {ch:16, type:"historical",  sev:"HIGH", flag:"⚠ Squad placed '3km east of Son My' — adjust to 'near the Son My perimeter'.",fixed:false},
  {ch:16, type:"name-error",  sev:"MED",  flag:"Duc's radio operator alternates 'Trong'/'Trung'. Standardize to 'Trong' throughout.",fixed:false},
  {ch:17, type:"historical",  sev:"MED",  flag:"Non-citizen recruits 1969 would process at MCRD San Diego first, not Camp Pendleton main gate.",fixed:false},
  {ch:21, type:"continuity",  sev:"MED",  flag:"Toy soldiers: 'lead' in Ch.3 vs 'plastic' in Ch.21. Standardize to LEAD.",fixed:false},
  {ch:23, type:"word-overuse",sev:"LOW",  flag:"'Faith' 11x in 5,505w (2.0/1k). Vary 2 instances.",fixed:false},
  {ch:24, type:"historical",  sev:"LOW",  flag:"Te Deum plausibility: add one line establishing French Catholic mission school history.",fixed:false},
  {ch:25, type:"historical",  sev:"HIGH", flag:"⚠ Siege of Khe Sanh described as '18 hours' — actual 77-day operation (Jan 21–Apr 9, 1968). Clarify: 'final eighteen hours of fifty-seven days.'",fixed:false},
  {ch:26, type:"word-overuse",sev:"MED",  flag:"'Brown' 8x in 400-word cluster (mid-chapter). Distribute more evenly.",fixed:false},
  {ch:29, type:"consistency", sev:"LOW",  flag:"Mortar caliber: '81mm' used but NVA standard is 82mm (Soviet-supplied). Standardize to 82mm for NVA-fired mortars.",fixed:false},
  {ch:32, type:"title-error", sev:"MED",  flag:"[v6 FIXED] Ch.32 heading 'CORRIDOR OF FIRE: THE MASTERPIEC' → 'THE MASTERPIECE' — corrected in v6 header-normalized docx.",fixed:true},
  {ch:34, type:"word-overuse",sev:"MED",  flag:"'Map' 12x in 5,366w (2.24/1k). Vary: 'the cardboard','the grid','operational theater'.",fixed:false},
  {ch:35, type:"consistency", sev:"LOW",  flag:"628 days: verify calculation from projected KIA date. Confirm mathematically precise.",fixed:false},
  {ch:40, type:"timeline",    sev:"HIGH", flag:"⚠ [v8 AUDIT] Ch.40 narrative compresses Henderson/Wilson/Martinez/Watkins/Williams/Herrera/O'Neil into one battle sequence. Ch.45 testimony assigns them separate dates and locations spanning Feb–Nov 1968. Add explicit date/location stamps to each death or reconcile Ch.45 testimony dates.",fixed:false},
  {ch:41, type:"incomplete",  sev:"CRIT", flag:"⚠ CRITICAL: Ch.41 'Adios Muchachos' extraction scene confirmed present and substantial. Ramos bathroom prayer confirmed delivered in Ch.44 (Day 2 gallery/recess). Verify final word count meets 5,000w target.",fixed:false},
  {ch:43, type:"title-error", sev:"MED",  flag:"Ch.42 title in TOC: 'The THE HEARING HALL' — duplicate article.",fixed:false},
  {ch:45, type:"title-error", sev:"MED",  flag:"[v6 FIXED] Ch.45 heading 'Unidos para SemprK' → 'Chapter 45: Unidos para Siempre' — corrected in v6 header-normalized docx.",fixed:true},
];

// ========== GLOSSARY ==========
export const GLOSSARY = [
  {term:"Yom'e",              cat:"yaqui",    def:"The Yaqui people's name for themselves — 'the people.'",freq:4,chapters:[1,7,18]},
  {term:"Maaso Kova",         cat:"yaqui",    def:"Sacred ceremonial deer head.",freq:1,chapters:[1]},
  {term:"Sewa",               cat:"yaqui",    def:"Flower — central Yaqui spiritual symbol.",freq:3,chapters:[1,2]},
  {term:"Pahko",              cat:"yaqui",    def:"Yaqui ceremonial gathering.",freq:2,chapters:[1]},
  {term:"Hiakim",             cat:"yaqui",    def:"Traditional Yaqui homeland across Sonora/Arizona.",freq:2,chapters:[1,7]},
  {term:"Tunnel rat",         cat:"military", def:"Soldier sent into Viet Cong tunnel networks. Physical metric weaponized against Chicano soldiers.",freq:12,chapters:[2,6,7,9,10]},
  {term:"MOS",                cat:"military", def:"Military Occupational Specialty. IBM 360's Diversity Project routes Chicano soldiers to MOS 11B.",freq:8,chapters:[3,4,18,19]},
  {term:"Firebase",           cat:"military", def:"Forward Operating Base — Firebase Charlie Reckoning is the squad's central location.",freq:18,chapters:[9,10,12,13,14,15]},
  {term:"DCAS",               cat:"military", def:"Defense Casualty Analysis System — 58,220 records. 84.9% classification failure for Hispanic/Latino soldiers.",freq:9,chapters:[3,4,8,19,40]},
  {term:"NIPS",               cat:"military", def:"NMCS Information Processing System 360 — IBM 360 database used by Pentagon.",freq:3,chapters:[3,4]},
  {term:"LZ",                 cat:"military", def:"Landing Zone. 'Hot LZ' = under fire.",freq:6,chapters:[10,31,32]},
  {term:"IIRIRA",             cat:"legal",    def:"1996 Illegal Immigration Reform and Immigrant Responsibility Act.",freq:7,chapters:[18,40,41]},
  {term:"50 USC §3802",       cat:"legal",    def:"Selective Service statute requiring ALL residents — citizen or not — to register for draft.",freq:3,chapters:[18,19]},
  {term:"IMMVI",              cat:"legal",    def:"Immigrant Military Members and Veterans Initiative — Biden 2021 EO.",freq:4,chapters:[40,41]},
  {term:"Ghost Protocol",     cat:"legal",    def:"Administrative practice of assigning a single operational identity to multiple service members. Four men used 'Sergeant George Ramos'—three KIA, one survivor (Joshua Sagasta). Revealed in Ch.45.",freq:5,chapters:[5,43,44,45]},
  {term:"¿Por cuántas lunas cargas tu dolor?",cat:"spanish",def:"How many moons have you carried your pain? — Ch.1. The manuscript's most important single line.",freq:1,chapters:[1]},
  {term:"Trece",              cat:"spanish",  def:"Thirteen — the Marines lost. Said in Spanish because English cannot hold the weight.",freq:4,chapters:[1,10,32,42]},
  {term:"Carnales",           cat:"spanish",  def:"Brothers (deep bond). The squad's internal address for each other.",freq:8,chapters:[10,14,21,27,30]},
  {term:"Los Obligados",      cat:"spanish",  def:"The Obligated/Compelled Ones — Mexican nationals drafted via 50 USC §3802.",freq:5,chapters:[18,19,20,27,37]},
  {term:"Chamoy",             cat:"spanish",  def:"Mexican condiment — Ch.14 Package Sacrament cross-cultural synthesis with cornbread.",freq:2,chapters:[14]},
  {term:"Te conozco",         cat:"spanish",  def:"'I know you' — Chieftain to Ramos, Ch.1. Recognition as spiritual diagnosis.",freq:1,chapters:[1]},
  {term:"Vessel",             cat:"manuscript",def:"Chieftain's designation for Ramos — one who carries the silenced dead within the body.",freq:12,chapters:[1,10,32,40,42]},
  {term:"The Mathematics of Revenge",cat:"manuscript",def:"Surviving past the algorithm's predicted death date. Love as counter-variable to IBM 360.",freq:6,chapters:[12,13,36,40]},
  {term:"628 days",           cat:"manuscript",def:"Exact days Martinez survives past algorithmically assigned KIA date. The number that breaks the machine.",freq:3,chapters:[36]},
  {term:"Diversity Project",  cat:"manuscript",def:"Crawford's fictional IBM 360 algorithm routing minority soldiers to high-mortality assignments.",freq:8,chapters:[3,4,9,19,36]},
  {term:"Los Records Mienten",cat:"manuscript",def:"The records lie. Ch.8 title (Guzman POV). Ramos also strikes the Senate table in Ch.45.",freq:2,chapters:[8,45]},
  {term:"Eighty-Seven",       cat:"manuscript",def:"87 Hispanic surnames found in 4 months of El Paso archives by Guzman. Empirical seed of the Guzman Methodology. Ch.8.",freq:1,chapters:[8]},
  {term:"Dona Ortiz",         cat:"manuscript",def:"Carmelo Ortiz. Mother of Ernesto Ortiz Fuentes KIA Vietnam. Mis-named death certificate triggers the Guzman Methodology. Ch.8.",freq:1,chapters:[8]},
  {term:"Cazador y Guardián", cat:"manuscript",def:"'The Hunter and the Guardian' — Miguel García and Jorge Barrón. Awarded Medal of Honor posthumously. Arc closes in Ch.39.",freq:6,chapters:[21,27,28,37,39,44]},
];

// ========== CHARACTER BIBLE ==========
export const CHARACTER_BIBLE = [
  {id:"ramos",    name:"SGT George Ramos (Joshua Sagasta)",  color:"gold",   arc:"COMPLETE",   flag:false,clmoe:0.04, note:"Ghost Protocol identity. Joshua Sagasta → George Ramos at MCRD 1965. Four men used the name. He is the survivor. Ch.45 restores his birth name."},
  {id:"crawford", name:"Capt. James Crawford III",           color:"red",    arc:"COMPLETE",   flag:false,clmoe:0.18, note:"Suicide note in Ch.45 testimony: 'I cannot calculate forgiveness.' Arc complete. Crawford's daughter and legacy addressed in Ch.44."},
  {id:"joshua",   name:"Joshua Sagasta",                     color:"purple", arc:"COMPLETE",   flag:false,clmoe:0.08, note:"Identity recovered in Ch.45 by Senate Resolution 17. His true name restored to official record."},
  {id:"miguel",   name:"Miguel García + Jorge Barrón",       color:"orange", arc:"COMPLETE",   flag:false,clmoe:0.06, note:"Both KIA in Ch.39 (When Compadres Fall). Miguel = shot under ribs. Jorge = two rounds through back. Medal of Honor posthumous. Ch.39 epilogue and Ch.44 ceremony."},
  {id:"duc",      name:"Major Pham Duc",                     color:"cyan",   arc:"COMPLETE",   flag:false,clmoe:0.10, note:"Testifies at hearing (Ch.43). Age 82. Confesses ordering Sacred Heart bombardment. 30 years farming rice near Hué. Arc complete."},
  {id:"chieftain",name:"The Yaqui Chieftain",                color:"teal",   arc:"COMPLETE",   flag:false,clmoe:0.03, note:"Minimal appearances, zero drift. Each word earned."},
  {id:"martinez", name:"PFC Martinez (Rafael Hernán)",       color:"pink",   arc:"COMPLETE",   flag:false,clmoe:0.07, note:"KIA Hill 51, Nov 17 1968 per Ch.45 testimony. 628 days paid off in Ch.36. Name on The Wall."},
  {id:"oneil",    name:"PFC O'Neil (Sean Patrick)",          color:"blue",   arc:"COMPLETE",   flag:false,clmoe:0.11, note:"KIA by sniper in Ch.40 after running 50m through fire to reach Ramos. 'Bless your heart, Sarge, but fuck you.' Ch.45: 'Killed in ambush, Hill 364, Feb 1968.' Timeline reconciliation needed."},
  {id:"ramirez",  name:"CPL Ramirez",                        color:"red",    arc:"COMPLETE",   flag:true, clmoe:0.09, note:"⚠ CRITICAL: Called 'Rodriguez' ~60% through Ch.10. KIA in Ch.11 (pink mist). St. Christopher medal recovered by Watkins."},
  {id:"lihn",     name:"Lihn Reynolds (Baby Lihn Nguyen)",   color:"teal",   arc:"COMPLETE",   flag:false,clmoe:0.02, note:"NEW [v8 AUDIT]: Reynolds's adopted daughter. Testifies Day 1 (Ch.43). Psychologist, age 54. Born Sacred Heart Orphanage. Father James Reynolds KIA May 17, 1968."},
  {id:"susan",    name:"Susan Martinez Acalin",              color:"gold",   arc:"COMPLETE",   flag:false,clmoe:0.02, note:"NEW [v8 AUDIT]: Miguel García's daughter. Testifies Day 2 (Ch.44). Attorney. 55 years old. Presents red dossier covering 55 years of litigation."},
  {id:"wilkins",  name:"James Wilkins (Door Gunner)",        color:"blue",   arc:"COMPLETE",   flag:false,clmoe:0.03, note:"NEW [v8 AUDIT]: 73rd extraction from a hot LZ. Covenant Ch.41: You live. You remember. You speak."},
  {id:"guzman",   name:"Dr. Rodolfo Guzman",                 color:"gold",   arc:"COMPLETE",   flag:false,clmoe:0.02, note:"[v12 Ch.8] Chicano professor. Watches broadcast with no raza names. Dona Ortiz visit triggers El Paso library investigation. 87 surnames in 4 months. Origin of Guzman Methodology. Wife: Lorena. Dog: Canelo."},
];

// ========== CONVERGENCE STREAMS ==========
export const CONVERGENCE_STREAMS = [
  {n:1,label:"DCAS Primary Records",     color:"red",    strength:99, desc:"58,220 records, 349 coded Hispanic (0.60%) — the core anomaly"},
  {n:2,label:"Guzman Methodology",       color:"orange", strength:92, desc:"1969: 19% of casualties, 12% of population — documented disparity"},
  {n:3,label:"LAE Database Cross-Ref",   color:"purple", strength:88, desc:"3,741 identified (6.43%) — highest estimate"},
  {n:4,label:"NARA Revised Count",       color:"teal",   strength:85, desc:"National Archives: 3,070 — independent institutional validation"},
  {n:5,label:"Catholic Proxy Signal",    color:"orange", strength:82, desc:"28.9% of DCAS coded Catholic (16,817) — ethnicity surrogate"},
  {n:6,label:"Geographic Clustering",   color:"blue",   strength:87, desc:"CA+TX+NM: SW states = 16.1% of all casualties"},
  {n:7,label:"Durazo Qualitative (NEW)", color:"gold",   strength:95, desc:"Semi-structured interviews — racial project mechanism confirmed."},
];

// ========== QUICK ACTIONS ==========
export const QUICK_ACTIONS = [
  {priority:1,action:"RESOLVE Ch.17 ↔ Ch.18 DUPLICATION (90%, 4,729w)",  impact:"structural", time:"2-3 days",domain:"All",        detail:"[v6 P0 VERIFIED] Ch.17 'Boundary Shift' and Ch.18 'Broken Wing' are near-total clones (~90% overlap, 4,729 exact-duplicate words). One is a forked draft of the other. Decision: is 'Broken Wing' a distinct chapter or a renamed copy of Ch.17? Pick canonical, delete duplicated body from the other. Removing the residue is error correction, not content cutting."},
  {priority:2,action:"RESOLVE Ch.14 ↔ Ch.22 DUPLICATION (86%, 3,040w)",  impact:"structural", time:"2-3 days",domain:"All",        detail:"[v6 P0 VERIFIED] Ch.14 'Package Sacrament' and Ch.22 'Don't Fuck with Familia' share 86% exact-duplicate overlap (3,040 words) across 8 chapters. Authorial decision required: deliberate callback (keep/compress) or revision paste (remove)? The distance makes this the judgment call. Read both chapters before deciding."},
  {priority:3,action:"RESOLVE Ch.26 ↔ Ch.27 DUPLICATION (67%, 2,375w)",  impact:"structural", time:"1-2 days",domain:"All",        detail:"[v6 P0 VERIFIED] Ch.26 'Echoes of an Empire' and Ch.27 'Hunters Geometry' share 67% exact-duplicate overlap (2,375 words, adjacent). Likely an unfinished chapter split. ~33% unique material in each side — merge unique content into one coherent chapter."},
  {priority:4,action:"✅ P0 HEADER ARTIFACTS — FIXED (v6 normalized docx 2026-06-06)",impact:"submission",time:"DONE",domain:"Formatting",detail:"[v6 VALIDATED] SGT_Ramos_v6_headers_normalized.docx · PASSED · 10 heading fixes: Ch11 colon+space, Ch17 double-space, Ch23 'Sparr1'→'Sparrow', Ch24 CAPS→Title, Ch32 'MASTERPIEC'→'MASTERPIECE', Ch36 trailing '34' removed, Ch37 'Reveng6'→'Revenge', Ch40 'chapter'→'Chapter', Ch44 'Chapter 44:THE'→'Chapter 44: THE', Ch45 'SemprK'→'Siempre'. · 5 residue draft paragraphs removed from body: Ch15 'Chapter 7: Red Clay', Ch16 'Chapter 16: My Lai', Ch17 'Chapter 17: Boundary Shift', Ch23 'CHAPTER 23: THE EAGLE...', Ch34 'Chapter 33: Sixty-Eight'. · Word count 243,242→243,218 (−24). Prose untouched. · STILL PENDING: Body deduplication of Ch14/22, Ch17/18, Ch26/27 — requires author decision."},
  {priority:5,action:"RECONCILE Ch.40 death timeline vs Ch.45",      impact:"continuity", time:"2 days",  domain:"Continuity", detail:"[v8 AUDIT HIGH] Ch.40 (Ares) compresses 7 Marine deaths into one battle. Ch.45 testimony assigns them separate dates: O'Neil=Feb 1968, Williams=Mar, Reynolds=May, Watkins=May, Henderson=Jun, Johnson=Jun, Herrera=Jul. Add explicit date/location stamps to each death scene or correct the Ch.45 testimony dates to match Ch.40's single-battle narrative."},
  {priority:3,action:"Seed Ghost Protocol Quartet foreshadowing",     impact:"+canon",     time:"2 days",  domain:"Structural", detail:"[v8 AUDIT HIGH] Ch.45 reveals 4 men used the 'George Ramos' identity. Three died. Plant seeds: a name discrepancy noticed by Roy in Ch.5; a second 'Ramos' casualty rumor in Ch.36; a filing anomaly mentioned in Ch.42."},
  {priority:4,action:"✅ Ch.32 + Ch.45 truncated titles — FIXED (v6 docx)",impact:"submission",time:"DONE",domain:"Formatting",detail:"[v6 FIXED] Ch.32 'THE MASTERPIEC'→'THE MASTERPIECE'. Ch.45 'Unidos para SemprK'→'Unidos para Siempre'. Both corrected in v6 header-normalized docx. Validated."},
  {priority:5,action:"Fix Ch.10 M249 SAW anachronism",                impact:"submission", time:"2 hrs",   domain:"Historical", detail:"Replace M249 SAW (adopted 1984) with M60 machine gun ('the pig'). Submission-blocking historical error."},
  {priority:6,action:"Fix Ch.10 Ramirez/Rodriguez name swap",          impact:"submission", time:"1 hr",    domain:"Continuity", detail:"CRITICAL: 'Ramirez' called 'Rodriguez' ~60% into chapter. Single find/replace + verify. Rodriguez=underage boy Ch.1. Ramirez=Ch.10/Ch.11 KIA."},
  {priority:7,action:"Verify Lalo ignorance chain (Chs 6–40)",         impact:"+canon",     time:"1 day",   domain:"Continuity", detail:"[v8 AUDIT] Ch.45 establishes Ramos did not know Lalo (Eduardo Reyes, two doors down on Boulder Street) was on Hill 51 until the Day 2 hearing. Audit Chs 6–40 to confirm Lalo's name never appears in Ramos's awareness."},
  {priority:8,action:"Fix Ch.25 Khe Sanh siege duration",              impact:"submission", time:"1 hr",    domain:"Historical", detail:"'18 hours' must read 'final eighteen hours of fifty-seven days.' Historical fact error."},
  {priority:9,action:"Major Duc Ch.40 presence",                       impact:"+0.5 Ω pt", time:"2 hrs",   domain:"Behavioral", detail:"One paragraph from Duc's POV at the Hearing Hall. Completes Vietnamese arc and seeds his Ch.43 testimony appearance."},
  {priority:10,action:"Ch.35 prose bridge insertion",                  impact:"+0.5 Ω pt", time:"3 hrs",   domain:"Narrative",  detail:"62% dialogue creates fatigue risk. Add two sensory prose paragraphs."},
];

// ========== TABS ==========
export const TABS = [
  {id:"overview",   label:"Overview",    group:null},
  {id:"chapters",   label:"Chapters",    group:null},
  {id:"domains",    label:"Domains",     group:null},
  {id:"flags",      label:"Flags",       group:null},
  {id:"pacing",     label:"Pacing",      group:null},
  {id:"scores",     label:"Scores",      group:null},
  {id:"arcs",       label:"Char Arcs",   group:"analysis"},
  {id:"emotion",    label:"Emotion",     group:"analysis"},
  {id:"nero",       label:"NERO",        group:"analysis"},
  {id:"ndr",        label:"NDR Map",     group:"analysis"},
  {id:"flesh",      label:"Flesh",       group:"analysis"},
  {id:"spss",       label:"SPSS",        group:"analysis"},
  {id:"clmoe",      label:"CL-MoE",      group:"analysis"},
  {id:"accuracy",   label:"Accuracy",    group:"analysis"},
  {id:"crossref",   label:"Archive XRef",group:"analysis"},
  {id:"characters", label:"Characters",  group:"platform"},
  {id:"glossary",   label:"Glossary",    group:"platform"},
  {id:"bugs",       label:"Bugs",        group:"platform"},
  {id:"modules",    label:"Modules",     group:"platform"},
  {id:"market",     label:"Market",      group:"platform"},
  {id:"canon",      label:"Canon",       group:"platform"},
  {id:"timeline",   label:"Timeline",    group:"platform"},
  {id:"grants",     label:"Grants",      group:"platform"},
  {id:"campaign",   label:"Campaign",    group:"platform"},
  {id:"phd",        label:"PhD",         group:"platform"},
  {id:"beta",       label:"Beta",        group:"research"},
  {id:"research",   label:"Research",    group:"research"},
  {id:"research_db",label:"ResearchDB",  group:"research"},
  {id:"search",     label:"Search",      group:"research"},
  {id:"narintel",   label:"Nar.Intel",   group:"research"},
  {id:"writer",     label:"Writer.AI",   group:"research"},
  {id:"motif",      label:"Motif Map",   group:"research"},
  {id:"charvoice",  label:"Voice Audit", group:"research"},
  {id:"report",     label:"Full Report", group:"research"},
  {id:"valence",    label:"Valence Map", group:"analysis"},
  {id:"chprogress", label:"Ch. Progress",group:"platform"},
  {id:"auditprog",  label:"Audit Progress",group:"platform"},
  {id:"litaudit",   label:"Lit. Audit",  group:"research"},
  {id:"canonworth", label:"Canon-Worth", group:"research"},
  {id:"platform",   label:"Platform",    group:"live"},
  {id:"aiintel",    label:"AI Intel",    group:"live"},
  {id:"foia",       label:"FOIA",        group:"platform"},
  {id:"veterans",   label:"Veterans",    group:"platform"},
  {id:"forensic",   label:"🔬 Forensic Audit", group:"live"},
  {id:"novil",      label:"NOVIL",       group:"live"},
  {id:"submission",  label:"📋 Submission", group:"live"},
  {id:"quarantine",  label:"🔒 Quarantine", group:"live"},
  {id:"comparison",   label:"⚖️ Compare",     group:"live"},
  {id:"dataintel",    label:"🌐 Data Intel",   group:"live"},
  {id:"bugfix",       label:"🔧 Bug Fix",     group:"live"},
  {id:"revision",     label:"✏️ Revision",  group:"live"},
  {id:"command",      label:"🎯 Command",   group:"live"},
  {id:"remediate",    label:"🔬 Remediate",  group:"live"},
  {id:"battle",        label:"⚔️ Battle Scenes", group:"live"},
  {id:"omegacls",      label:"📈 Ω/CLS Trend",   group:"analysis"},
  {id:"mktcal",        label:"📅 Mkt Calendar",  group:"live"},
  {id:"claims",        label:"📋 Claims Ledger", group:"live"},
  {id:"dupmap",        label:"🔁 Dup Map",       group:"live"},
  {id:"execboard",     label:"🎖️ Exec Decision",  group:"live"},
];