// ============================================================
// V4 SNAPSHOT — SGT GEORGE RAMOS: THE MATHEMATICS OF VIETNAM
// Captured: 2026-05-27 — before v5 DOCX audit overwrite
// Purpose: regression detection, revision evidence, LITCENTRAL continuity
// DO NOT EDIT THIS FILE — it is a timestamped audit baseline
// ============================================================

export const V4_SNAPSHOT_DATE = '2026-05-27';
export const V4_BASELINE = 105.18;
export const V4_PROJ_MEAN = 106.54;
export const V4_WORD_COUNT = 241117;
export const V4_CHAPTERS_COMPLETE = 16; // chapters at GOLD+ or above

// Per-chapter v4 scores — { n, title, act, oc (omega current), cls, bis, sii, mrf, tier }
export const V4_CHAPTER_SCORES = [
  {n:1,  title:"The Sacred Mountain Revelation", act:"I",   oc:105.17, cls:86, bis:87, sii:82, mrf:82, tier:"GOLD"},
  {n:2,  title:"DESCENT INTO BAPTISM",           act:"I",   oc:104.66, cls:84, bis:89, sii:78, mrf:80, tier:"GOLD"},
  {n:3,  title:"THE GENOCIDE ALGORITHM",         act:"I",   oc:104.99, cls:90, bis:83, sii:79, mrf:83, tier:"GOLD"},
  {n:4,  title:"Pentagon, December 1969",        act:"I",   oc:105.78, cls:96, bis:87, sii:72, mrf:86, tier:"GOLD+"},
  {n:5,  title:"The Ghost Protocol",             act:"I",   oc:104.97, cls:84, bis:89, sii:80, mrf:82, tier:"GOLD"},
  {n:6,  title:"Crucible Theorem",               act:"I",   oc:105.62, cls:85, bis:90, sii:80, mrf:88, tier:"GOLD+"},
  {n:7,  title:"The Boulevard Theorem",          act:"I",   oc:105.05, cls:83, bis:89, sii:80, mrf:85, tier:"GOLD+"},
  {n:8,  title:"Los Records Mienten",            act:"I",   oc:105.61, cls:84, bis:88, sii:87, mrf:84, tier:"GOLD+"},
  {n:9,  title:"FIRST BLOOD",                    act:"I",   oc:108.85, cls:87, bis:92, sii:79, mrf:93, tier:"OMEGA ELITE"},
  {n:10, title:"The Pendejo Squad",              act:"I",   oc:104.81, cls:82, bis:88, sii:80, mrf:85, tier:"GOLD"},
  {n:11, title:"Contact Contact",                act:"I",   oc:106.18, cls:85, bis:94, sii:84, mrf:84, tier:"GOLD+"},
  {n:12, title:"Red Truth Revolution",           act:"I",   oc:105.23, cls:84, bis:90, sii:80, mrf:84, tier:"GOLD+"},
  {n:13, title:"The Walls Speak in Red",         act:"I",   oc:104.82, cls:83, bis:87, sii:80, mrf:85, tier:"GOLD"},
  {n:14, title:"Package Sacrament",              act:"I",   oc:105.39, cls:83, bis:90, sii:84, mrf:83, tier:"GOLD+"},
  {n:15, title:"Move Like Water",                act:"I",   oc:107.04, cls:87, bis:95, sii:82, mrf:94, tier:"OMEGA ELITE"},
  {n:16, title:"My Lai Massacre",                act:"I",   oc:104.04, cls:90, bis:87, sii:75, mrf:82, tier:"GOLD"},
  {n:17, title:"Boundary Shift",                 act:"I",   oc:103.91, cls:88, bis:88, sii:75, mrf:82, tier:"GOLD"},
  {n:18, title:"Broken Wing",                    act:"I",   oc:104.50, cls:83, bis:86, sii:80, mrf:82, tier:"GOLD"},
  {n:19, title:"Los Obligados",                  act:"II",  oc:107.12, cls:85, bis:92, sii:98, mrf:83, tier:"OMEGA ELITE"},
  {n:20, title:"THE GENESIS EQUATION",           act:"II",  oc:105.91, cls:87, bis:96, sii:77, mrf:82, tier:"GOLD+"},
  {n:21, title:"El Cazador y El Guardián",       act:"II",  oc:106.02, cls:85, bis:90, sii:86, mrf:86, tier:"GOLD+"},
  {n:22, title:"Don't Fuck with Familia",        act:"II",  oc:105.48, cls:83, bis:93, sii:87, mrf:90, tier:"GOLD+"},
  {n:23, title:"The Eagle and the Sparrow",      act:"II",  oc:104.48, cls:83, bis:87, sii:80, mrf:80, tier:"GOLD"},
  {n:24, title:"SACRED HEART BRIEFING",          act:"II",  oc:102.51, cls:84, bis:93, sii:80, mrf:83, tier:"GOLD"},
  {n:25, title:"Sacred Heart",                   act:"II",  oc:104.65, cls:84, bis:87, sii:79, mrf:82, tier:"GOLD"},
  {n:26, title:"Echoes of an Empire",            act:"II",  oc:105.19, cls:83, bis:90, sii:81, mrf:84, tier:"GOLD+"},
  {n:27, title:"Hunter's Geometry",              act:"II",  oc:106.47, cls:92, bis:88, sii:87, mrf:82, tier:"GOLD+"},
  {n:28, title:"Cruzan, o nadie cruzan",         act:"II",  oc:105.05, cls:84, bis:87, sii:85, mrf:80, tier:"GOLD+"},
  {n:29, title:"MATHEMATICS OF REVOLUTION",      act:"II",  oc:104.75, cls:84, bis:89, sii:79, mrf:80, tier:"GOLD"},
  {n:30, title:"ORCHESTRATING NECESSARY EVIL",   act:"II",  oc:104.38, cls:82, bis:87, sii:78, mrf:83, tier:"GOLD"},
  {n:31, title:"RETREAT, HELL",                  act:"III", oc:104.59, cls:86, bis:90, sii:82, mrf:83, tier:"GOLD"},
  {n:32, title:"CORRIDOR OF FIRE",               act:"III", oc:105.18, cls:85, bis:88, sii:83, mrf:81, tier:"GOLD+"},
  {n:33, title:"Angels from Above",              act:"III", oc:104.79, cls:83, bis:87, sii:79, mrf:86, tier:"GOLD"},
  {n:34, title:"Sixty-Eight",                    act:"III", oc:102.69, cls:87, bis:90, sii:81, mrf:84, tier:"GOLD"},
  {n:35, title:"The Birthday Brief",             act:"III", oc:104.89, cls:83, bis:91, sii:80, mrf:79, tier:"GOLD"},
  {n:36, title:"Mission Execution",              act:"III", oc:104.00, cls:82, bis:93, sii:80, mrf:79, tier:"GOLD"},
  {n:37, title:"The Mathematics of Revenge",     act:"III", oc:104.62, cls:83, bis:88, sii:78, mrf:83, tier:"GOLD"},
  {n:38, title:"Last Dance",                     act:"III", oc:102.26, cls:84, bis:92, sii:80, mrf:81, tier:"GOLD"},
  {n:39, title:"When Compadres Fall",            act:"III", oc:107.06, cls:85, bis:89, sii:96, mrf:90, tier:"OMEGA ELITE"},
  {n:40, title:"Ares Death of a God",            act:"III", oc:106.82, cls:86, bis:92, sii:84, mrf:88, tier:"GOLD+"},
  {n:41, title:"Adios Muchachos",                act:"III", oc:106.10, cls:85, bis:90, sii:83, mrf:90, tier:"GOLD+"},
  {n:42, title:"Sacred Smoke",                   act:"III", oc:104.66, cls:84, bis:86, sii:82, mrf:80, tier:"GOLD"},
  {n:43, title:"RESURRECTION",                   act:"III", oc:104.26, cls:84, bis:85, sii:78, mrf:81, tier:"GOLD"},
  {n:44, title:"THE EXILE PATRIOTS",             act:"III", oc:104.91, cls:83, bis:84, sii:85, mrf:85, tier:"GOLD"},
  {n:45, title:"Unidos para Siempre",            act:"III", oc:106.25, cls:86, bis:85, sii:84, mrf:99, tier:"GOLD+"},
];